config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'
  get 'bookmarks/new'
  get 'bookmarks/create'
  get 'bookmarks/destroy'
  get 'lists/index'
  get 'lists/create'
  get 'lists/new'
  get 'lists/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lists, only: [:show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

# shows all bookmarks in lists#show
# able to add/delete bookmarks in lists#show

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie_id, scope: [:list_id]
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
    @movies = Movie.all # able to select movie from list of movies
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list

    if @bookmark.save
      redirect_to @bookmark.list
    else
      render "lists/show"
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = @bookmark.list
    @bookmark.destroy
    redirect_to @list
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def new
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_bookmark.html.erb
<div class="col-4">
  <div class="card">
    <%= image_tag(bookmark.movie.poster_url)%>
    <h3><strong><%= bookmark.movie.title %></strong></h3>
    <p><%= bookmark.movie.rating %> ⭐️</p>
    <small><%= bookmark.movie.overview %></small>

    <div class="d-flex justify-content-between">
      <p class="lead"><i class="fas fa-quote-left"></i><%= bookmark.comment %><i class="fas fa-quote-right"></i></p>
      <%= link_to "Delete", bookmark_path(bookmark), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-warning" %>
    </div>
  </div>
</div>

app/views/bookmarks/create.html.erb
<h1>Bookmarks#create</h1>
<p>Find me in app/views/bookmarks/create.html.erb</p>

app/views/bookmarks/destroy.html.erb
<h1>Bookmarks#destroy</h1>
<p>Find me in app/views/bookmarks/destroy.html.erb</p>

app/views/bookmarks/new.html.erb
<div class="container">
  <h1>Create a new bookmark</h1>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.association :movie, prompt: "Choose the movie to bookmark" %>
    <%= f.input :comment %>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
  <%= link_to "Return to list", list_path(@list), class: "btn btn-secondary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_list.html.erb
<div class="col-4">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://source.unsplash.com/random/360x180)">
  <%= link_to list.name, list_path(list) %>
</div>
</div>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/index.html.erb
<div class="container">
  <div class="row">
    <%= render @lists %>
  </div>
  <%= link_to "Create a new list", lists_new_path, class: "btn btn-primary" %>
</div>

<%= cl_image_tag("sample") %>

app/views/lists/new.html.erb
<div class="container">
  <h1>Create a new list</h1>
  <%= simple_form_for @list do |f| %>
    <%= f.input :name %>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
  <%= link_to "Return to list", lists_path, class: "btn btn-secondary" %>
</div>

app/views/lists/show.html.erb
<div class="container">
  <%= render @list %>
    <%= link_to "Add a new movie", new_list_bookmark_path(@list), class: "btn btn-primary" %>
    <%= link_to "Return to all lists", lists_path, class: "btn btn-secondary" %>
  <div class="row">
    <%= render @list.bookmarks %>
  </div>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.association :movie, prompt: "Choose the movie to bookmark" %>
    <%= f.input :comment %>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
</div>